POST http://localhost:8010/monitors
Content-Type: application/json

{
  "id": "mymonitors.mymonitor-2",
  "type": "docker",
  "schedule": "* * * * *",
  "definition": {
    "image": "nginx:latest",
    "dockerEnv": {
      "var1": "var1",
      "var2": "var2"
    }
  }
}

### Get single monitor
GET http://localhost:8010/monitors/mymonitors.mymonitor-2

### Get some monitors
GET http://localhost:8010/monitors?pageSize=2&pageIndex=0&contains=-2


### Get monitor from sgc/e2e
GET http://localhost:8010/monitors/monitors.mymonitor2
