### Create parent target
POST http://localhost:8010/targets
Content-Type: application/json

{
  "id": "mytargets",
  "description": "this is my parent target",
  "status": 5,
  "monitor": {
    "monitorId": "mymonitors.mymonitor-2"
  }
}

### Create parent target
POST http://localhost:8010/targets
Content-Type: application/json

{
  "id": "mytargets1",
  "description": "this is my parent target",
  "children": [
    {
      "id": "mytargets1.child",
      "description": "this is my parent target"
    }
  ]
}

### Create child target
POST http://localhost:8010/targets
Content-Type: application/json

{
  "id": "mytargets.mytarget-2",
  "description": "this is my target",
  "status": 5,
  "monitor": {
    "monitorId": "mymonitors.mymonitor-2"
  }
}

### Create child2 target
POST http://localhost:8010/targets
Content-Type: application/json

{
  "id": "mytargets.MYTARGET-1",
  "status": 5,
  "description": "this is my target",
  "monitor": {
    "monitorId": "mymonitors.mymonitor-2"
  }
}

### Create child3 target
POST http://localhost:8010/targets
Content-Type: application/json

{
  "id": "mytargets.MYTARGET-3",
  "status": 40,
  "description": "this is my target",
  "monitor": {
    "monitorId": "mymonitors.mymonitor-2"
  }
}

### Create child 3rd level target
POST http://localhost:8010/targets
Content-Type: application/json

{
  "id": "mytargets.mytarget-2.subtarget1",
  "description": "this is my target",
  "monitor": {
    "monitorId": "mymonitors.mymonitor-2"
  }
}

### Get the child target
GET http://localhost:8010/targets/mytargets


### Get the child target
GET http://localhost:8010/targets?pageSize=4&pageIndex=0&contains=mytarget

### Patch a target
PATCH http://localhost:8010/targets/mytargets.mytarget-1
Content-Type: application/json

{
  "status": 100
}