### Create parent target
POST http://localhost:8080/targets
Content-Type: application/json

{
  "id": "mytargets2",
  "description": "this is my parent target",
  "monitor": {
    "monitorId": "mymonitors.mymonitor-2"
  }
}

### Create parent target
POST http://localhost:8080/targets
Content-Type: application/json

{
  "id": "mytargets1",
  "description": "this is my parent target",
  "children": [
    {
      "id": "mytargets1.child",
      "description": "this is my parent target"
    }
  ]
}

### Create child target
POST http://localhost:8080/targets
Content-Type: application/json

{
  "id": "mytargets.mytarget-2",
  "description": "this is my target",
  "monitor": {
    "monitorId": "mymonitors.mymonitor-2"
  }
}

### Create child2 target
POST http://localhost:8080/targets
Content-Type: application/json

{
  "id": "mytargets.MYTARGET-1",
  "description": "this is my target",
  "monitor": {
    "monitorId": "mymonitors.mymonitor-2"
  }
}

### Create child 3rd level target
POST http://localhost:8080/targets
Content-Type: application/json

{
  "id": "mytargets.mytarget-2.subtarget1",
  "description": "this is my target",
  "monitor": {
    "monitorId": "mymonitors.mymonitor-2"
  }
}


### Get the child target
GET http://localhost:8080/targets/mytargets


### Get the child target
GET http://localhost:8080/targets?pageSize=2&pageIndex=0&contains=mytarget
